namespace: fr_pursuit
name: wsl
version: 0.1.0
readme: README.md
authors:
- Pursuit (@fr-Pursuit)
description: This collection adds a new connection type, 'local_wsl', used to connect to the local Windows host from WSL.
license:
- GPL-3.0-or-later
tags: ["windows", "wsl", "local"]
repository: https://github.com/fr-Pursuit/ansible-wsl
issues: https://github.com/fr-Pursuit/ansible-wsl/issues
